HW2 is completed
Ayr2017/golang-professional pull request #2
Opened 2023-08-11 08:53 UTC by Ayr2017

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-12 06:33 UTC, vladislavmass requested changes
Хорошее начало. Порадовал свой метод `isDigit`. Работа пока принять не могу так как нет новых тестов, а также код некорректно обрабатывает следующий тест кейс `{input: "aab2", expected: "aabb"}`

2023-08-12 06:33 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		if i == 0 && isDigit(byteSlice[i]) {
Зачем на каждом шаге цикла делать проверку что `index==0`? Предлагаю сделать это перед циклом

2023-08-12 06:33 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		if i < len(byteSlice)-2 {
Вашим коллегам придется поломать голову почему тут `-2`. В программирование это называют магические числа и их использование является плохим тоном

2023-08-12 06:33 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +func isDigit(ch rune) bool {
Классная идея. В данном случае действительно такая проверка будет работа эффективнее и правильнее чем проверка из библиотеки.

2023-08-13 06:12 UTC, Ayr2017 commented on hw02_unpack_string/unpack.go
> +func isDigit(ch rune) bool {
при поиске решений в интернете встречаю проверку такую проверку **_, err := strconv.Atoi(string(ch))** 
далее если нет ошибки, значит число. Это я вынес отдельно в функцию, вместо проверки символа. Не знаю насколько это эффективно, но вставка такой проверки прямо в условие if ... усложняет восприятие.
Про какую проверку из библиотеки Вы имели ввиду?

2023-08-13 06:15 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +func isDigit(ch rune) bool {
Я говорил про ` strconv.Atoi()`. Но повторюсь еще раз ваш вариант в данном случае лучше и советовал бы его вернуть

2023-08-13 06:24 UTC, vladislavmass requested changes
Хорошая работа. Пока принять не могу, так как нет новых тестов( предложенный мной не в счет)

2023-08-13 06:24 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	byteSlice := []rune(inputString)
А причем тут byte? Имя переменной не соответствует ее содержанию

2023-08-13 06:24 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +			if err != nil {
Обработка ошибок обычно делается сразу после вызовы функции, откуда она пришла. Так что этот код лучше поместить на 27 строку

2023-08-13 06:24 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +			sb.WriteString(string(byteSlice[i]))
Вызов метода WirteRune даст такой же эффект но без лишних затрат на конвертацию в строку.

2023-08-13 10:36 UTC, vladislavmass approved these changes
Работа принята. 10/10

2023-08-14 05:20 UTC, merged